name: pml
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Basic dependencies
  - python=3.8
  - pip
  - numpy
  - scipy
  # Packages for visualization
  - matplotlib
  - pandas
  - jupyter
  # Wave-U-Net dependencies
  - pytorch=1.10
  - torchvision
  - cudatoolkit=11.3
  - tensorboard
  - future
  - librosa
  - pysoundfile
  - ffmpeg=4.4
  - pyyaml # musdb requirement
  - musdb
  - h5py
  - tqdm
  - sortedcontainers
  # Others
  - torchaudio # Needed ?
  - pip:
      - museval



